module:
  address: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_classes: 0
  block_content: 0
  block_content_permissions: 0
  bootstrap_layout_builder: 0
  bootstrap_styles: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  components: 0
  config: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  flexslider: 0
  help: 0
  history: 0
  image: 0
  jquery_ui: 0
  jquery_ui_checkboxradio: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  media_library_theme_reset: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  search: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  taxonomy_menu_ui: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_bootstrap: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_node: 0
  webform_ui: 0
  workflows: 0
  ds: 1
  pathauto: 1
  webform_bootstrap: 1
  views: 10
  standard: 1000
theme:
  bartik: 0
  seven: 0
  stable: 0
  classy: 0
  bootstrap_barrio: 0
  jim_barrio: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
