id: whatsapp
label: whatsapp
ui_limit: ''
properties:
  content: "<html> <a href=\"https://wa.me/31630644641\" style=\"text-decoration: none;\" target=\"_blank\"> \r\n\t <img src=\"https://i.ibb.co/N9P0K9H/239px-Whats-App-svg.png\" width=\"35\" height=\"35\"/>\r\n</a> </html>"
type: twig
type_label: 'Twig field'
entities:
  block_content: block_content
